name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    PROJECT_NAME: fanqie

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - id: commit-hash
              uses: prompt/actions-commit-hash@v3
            - name: Build
              run: |
                  echo "Build on ${{ matrix.os }} with commit hash ${{ steps.commit-hash.outputs.short }}"
                  echo ${{ runner.os }}
                  cmake --build --preset=${{ runner.os }}
