name: Release

env:
    PROJECT_NAME: fanqie

on:
    workflow_run:
        workflows: ["Build"]
        types:
            - completed
    push:
        tags:
            - "v*"

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            - id: commit-hash
              uses: prompt/actions-commit-hash@v3
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Create Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  commit_hash: ${{ steps.commit-hash.outputs.commit_hash }}
              run: |
                  gh release create "$GITHUB_REF_NAME" \
                  --repo "$GITHUB_REPOSITORY" \
                  --title "$GITHUB_REF_NAME (${{ env.commit_hash }})"
                  --generate-notes \
                  --latest \

    upload-release-asset:
        runs-on: ubuntu-latest
        needs: create-release
        steps:
            - name: Upload Release Asset
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh release upload "$GITHUB_REF_NAME" \
                  --repo "$GITHUB_REPOSITORY" \
                  ./build/Linux/${{ env.PROJECT_NAME }}.so \
                  ./build/Windows/${{ env.PROJECT_NAME }}.dll \
